import { createClient } from "npm:@supabase/supabase-js@2";
import { sendLovableEmail } from "npm:@lovable.dev/email-js";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { recipientEmail, hotelName, downloadUrl } = await req.json();

    if (!recipientEmail || !hotelName || !downloadUrl) {
      return new Response(
        JSON.stringify({ error: "Missing required fields" }),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const apiKey = Deno.env.get("LOVABLE_API_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const messageId = `report-share-${crypto.randomUUID()}`;

    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f8fafc;">
        <div style="background-color: #1e293b; padding: 24px; border-radius: 12px 12px 0 0; text-align: center;">
          <h1 style="color: #ffffff; margin: 0; font-size: 22px;">Hotel Online Score Card</h1>
          <p style="color: #94a3b8; margin: 8px 0 0; font-size: 14px;">Performance Report</p>
        </div>
        <div style="background-color: #ffffff; padding: 32px; border-radius: 0 0 12px 12px; border: 1px solid #e2e8f0; border-top: none;">
          <p style="color: #334155; font-size: 16px; line-height: 1.6;">
            A Hotel Online Score Card report has been shared with you for <strong>${hotelName}</strong>.
          </p>
          <p style="color: #334155; font-size: 16px; line-height: 1.6;">
            This report includes scores and analysis for SEO, website quality, reviews, OTA performance, and social media presence.
          </p>
          <div style="text-align: center; margin: 32px 0;">
            <a href="${downloadUrl}" 
               style="display: inline-block; background-color: #1e293b; color: #ffffff; text-decoration: none; padding: 14px 32px; border-radius: 8px; font-size: 16px; font-weight: 600;">
              Download PDF Report
            </a>
          </div>
          <p style="color: #94a3b8; font-size: 12px; text-align: center; margin-top: 24px;">
            This report was generated by <a href="https://thehotelinsider.co" style="color: #1e293b;">The Hotel Insider</a>
          </p>
        </div>
      </div>
    `;

    const plainText = `Hotel Online Score Card report for ${hotelName}.\n\nDownload your PDF report: ${downloadUrl}\n\nGenerated by The Hotel Insider – thehotelinsider.co`;

    await sendLovableEmail(
      {
        to: recipientEmail,
        from: "Hotel Score Card <noreply@notify.go1.thehotelinsider.co>",
        sender_domain: "notify.go1.thehotelinsider.co",
        subject: `Hotel Online Score Card – ${hotelName}`,
        html: emailHtml,
        text: plainText,
        purpose: "transactional",
        label: "report-share",
        message_id: messageId,
      },
      { apiKey, sendUrl: Deno.env.get("LOVABLE_SEND_URL") }
    );

    await supabase.from("report_shares").insert({
      recipient_email: recipientEmail,
      hotel_name: hotelName,
      download_url: downloadUrl,
    });

    await supabase.from("email_send_log").insert({
      message_id: messageId,
      template_name: "report-share",
      recipient_email: recipientEmail,
      status: "sent",
      metadata: { hotelName, downloadUrl },
    });

    console.log("Report email sent:", { recipientEmail, hotelName, messageId });

    return new Response(JSON.stringify({ success: true, downloadUrl }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error:", error);
    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : String(error),
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
